/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'docs/intro',
    },
    {
      type: 'category',
      label: '00_Introduction',
      items: [
        'docs/00_Introduction/00_Objectif_du_cours',
        'docs/00_Introduction/01_Organisation_de_la_formation',
      ],
    },
    {
      type: 'category',
      label: '01_Présentation_de_Kubernetes_et_Openshift',
      items: [
        'docs/01_Présentation_de_Kubernetes_et_Openshift/00_Presentation_d_Openshift',
        'docs/01_Présentation_de_Kubernetes_et_Openshift/01_Quiz_Presentation_d_Openshift',
        'docs/01_Présentation_de_Kubernetes_et_Openshift/02_Exploration_de_la_console',
        'docs/01_Présentation_de_Kubernetes_et_Openshift/03_Exercice_guidé_Exploration_de_la_console',
        'docs/01_Présentation_de_Kubernetes_et_Openshift/04_Architecture_Openshift_et_Kubernetes',
        'docs/01_Présentation_de_Kubernetes_et_Openshift/05_Quiz_Architecture_Openshift_et_Kubernetes',
        'docs/01_Présentation_de_Kubernetes_et_Openshift/06_Résumé',
      ],
    },
    {
      type: 'category',
      label: '02_Interface_et_ligne_de_commande',
      items: [
        'docs/02_Interface_et_ligne_de_commande/00_Intéragir_avec_la_ligne_de_commande',
        'docs/02_Interface_et_ligne_de_commande/01_Exerice_guidé_Intéragir_avec_la_ligne_de_commande',
        'docs/02_Interface_et_ligne_de_commande/02_Examen_des_ressources_Kubernetes',
        'docs/02_Interface_et_ligne_de_commande/03_Exercice_guidé_Examen_des_ressources_Kubernetes',
        'docs/02_Interface_et_ligne_de_commande/04_Résumé',
      ],
    },
    {
      type: 'category',
      label: '03_Executez_des_applications_conteneurisé',
      items: [
        'docs/03_Executez_des_applications_conteneurisé/00_Les_Workloads_dans_Openshift',
        'docs/03_Executez_des_applications_conteneurisé/01_Quiz_Les_Workloads_dans_Openshift',
        'docs/03_Executez_des_applications_conteneurisé/02_Les_deployment_et_les_daemonset',
        'docs/03_Executez_des_applications_conteneurisé/03_Exercice_guidé_Les_deployment_et_les_daemonset',
        'docs/03_Executez_des_applications_conteneurisé/04_Les_statefulset',
        'docs/03_Executez_des_applications_conteneurisé/05_Exercice_guidé_Les_statefulset',
        'docs/03_Executez_des_applications_conteneurisé/06_Résumé',
      ],
    },
    {
      type: 'category',
      label: '04_Les_réseaux_dans_openshift',
      items: [
        'docs/04_Les_réseaux_dans_openshift/00_Les_sdn_dans_openshift',
        'docs/04_Les_réseaux_dans_openshift/01_Quiz_Les_sdn_dans_openshift',
        'docs/04_Les_réseaux_dans_openshift/02_Les_réseaux_de_pods_et_de_services',
        'docs/04_Les_réseaux_dans_openshift/03_Exercice_guidé_Les_réseaux_de_pods_et_de_services',
        'docs/04_Les_réseaux_dans_openshift/04_Résumé',
      ],
    },
    {
      type: 'category',
      label: '05_Gestion_du_stockage',
      items: [
        'docs/05_Gestion_du_stockage/00_Les_configmap_et_les_secrets_dans_openshift',
        'docs/05_Gestion_du_stockage/01_Exercice_guidé_Les_configmap_et_les_secrets_dans_openshifts',
        'docs/05_Gestion_du_stockage/02_Approvisionnement_des_volumes_de_donnés_persistantes',
        'docs/05_Gestion_du_stockage/03_Selection_d_une_classe_de_stockage',
        'docs/05_Gestion_du_stockage/04_Exercice_guidé_pv_pvc_storage_class',
        'docs/05_Gestion_du_stockage/05_Résumé',
      ],
    },
    {
      type: 'category',
      label: '06_Configuration_de_la_fiabilité_des_applications',
      items: [
        'docs/06_Configuration_de_la_fiabilité_des_applications/00_Utilisation_des_probes_dans_Kubernetes',
        'docs/06_Configuration_de_la_fiabilité_des_applications/01_Exercice_guidé_Utilisation_des_probes_dans_Kubernetes',
        'docs/06_Configuration_de_la_fiabilité_des_applications/02_Réservation_et_Limitation_de_capacité_de_calcul_pour_les_applications',
        'docs/06_Configuration_de_la_fiabilité_des_applications/03_Exercice_guidé_Réservation_et_Limitation_de_capacité_de_calcul_pour_les_applications',
        'docs/06_Configuration_de_la_fiabilité_des_applications/04_Mise_a_l_echelle_automatique_des_applications',
        'docs/06_Configuration_de_la_fiabilité_des_applications/06_Résumé',
      ],
    },
    {
      type: 'category',
      label: '07_Gestion_et_administration_du_cluster',
      items: [
        'docs/07_Gestion_et_administration_du_cluster/00_User_management',
        'docs/07_Gestion_et_administration_du_cluster/01_Exercice_guidé_user_management',
        'docs/07_Gestion_et_administration_du_cluster/02_Observabilité_du_cluster',
        'docs/07_Gestion_et_administration_du_cluster/03_Exercice_guidé_Observabilité_du_cluster',
        'docs/07_Gestion_et_administration_du_cluster/04_Node_MachineSet_MachineConfigs',
        'docs/07_Gestion_et_administration_du_cluster/05_Exercice_guidé_MachineSet_MachineConfigs.md',
        'docs/07_Gestion_et_administration_du_cluster/06_Gestion_des_mises_a_jours',
        'docs/07_Gestion_et_administration_du_cluster/07_Quiz_gestion',
        'docs/07_Gestion_et_administration_du_cluster/08_Résumé',
      ],
    },
  ],
   
};

export default sidebars;
